{ AUTO-GENERATED }

unit res_enum;

interface

type
	spriteInfo = (
		SPRITE_NONE_0,
		SPRITE_PLAYER_IDLE0_0,
		SPRITE_PLAYER_IDLE1_0,
		SPRITE_PLAYER_IDLE2_0,
		SPRITE_PLAYER_WALK0_0,
		SPRITE_PLAYER_WALK0_1,
		SPRITE_PLAYER_WALK0_2,
		SPRITE_PLAYER_WALK0_3,
		SPRITE_PLAYER_WALK1_0,
		SPRITE_PLAYER_WALK1_1,
		SPRITE_PLAYER_WALK1_2,
		SPRITE_PLAYER_WALK1_3,
		SPRITE_PLAYER_WALK2_0,
		SPRITE_PLAYER_WALK2_1,
		SPRITE_PLAYER_WALK2_2,
		SPRITE_PLAYER_WALK2_3,
		SPRITE_PLAYER_WALK3_0,
		SPRITE_PLAYER_WALK3_1,
		SPRITE_PLAYER_WALK3_2,
		SPRITE_PLAYER_WALK3_3
	);

	spriteState = (
		SPRITE_NONE,
		SPRITE_PLAYER_IDLE0,
		SPRITE_PLAYER_IDLE1,
		SPRITE_PLAYER_IDLE2,
		SPRITE_PLAYER_WALK0,
		SPRITE_PLAYER_WALK1,
		SPRITE_PLAYER_WALK2,
		SPRITE_PLAYER_WALK3
	);

	entityState = (
		STATE_NONE,
		STATE_PLAYER_IDLE0,
		STATE_PLAYER_IDLE1,
		STATE_PLAYER_IDLE2,
		STATE_PLAYER_IDLE3,
		STATE_PLAYER_WALK0,
		STATE_PLAYER_WALK1,
		STATE_PLAYER_WALK2,
		STATE_PLAYER_WALK3
	);

implementation
end.
